title: Divya's Amazing Blog!
author: danant01
email: dananth@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This is going to be a very simple blog with some facts about me.

# social links
twitter_username: divyaa_9 # DO NOT include the @ character, or else the build will fail!
github_username:  dananth01 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
