title: Divya's Amazing Blog!
author: dananth01
email: dananth@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  I will be posting some basic information about myself on my blog! 

# social links
twitter_username: divyaa_9 # DO NOT include the @ character, or else the build will fail!
github_username:  dananth01 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
